version: '3.7'

services:
  dataanalysis:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - cassandra
      - pulsar

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - "6650:6650"
      - "8080:8080"  # Mantenha esta porta como estava originalmente
    environment:
      - PULSAR_MEM=" -Xms128m -Xmx256m -XX:MaxDirectMemorySize=128m"
